### ISSUE TITLE
Replace JSON with Flatbuffers

### ISSUE THREAD

**Issue by failuer** [alloverse/allonet#24]
- [x] Stub out missing methods
- [ ] Make the server run okay
    - [x] spawn entity
    - [x] Change components
    - [ ] removeEntity() 
    - [ ] add_property_animation_interaction
    - [ ] remove_property_animation_interaction
    - [ ] list_agents_interaction 
- [x] Merge luajitted master to flatbuffer branch
- [ ] Add flatbuffer support to the new ffi API
    - [ ] **NTH** maybe investigate IterationVisitor
    - [ ] client must calculate a state_diff from a previous state
        - [x] new_entities
        - [x] removed_entities
        - [x] new_components
        - [x] removed_components
        - [x] updated_components using UnPack
        - [ ] **NTH** figure out how to compare component Tables so we can implement updated_components
    - [x] Put a flatbuffer pointer in `olddata` and `newdata` in `component_ref`
    - [ ] use this diff in `Client:updateState`
- [ ] Fix `allosim_simulate_root_pose`
- [ ] Fix simulate to work on client
- [ ] Fix simulate to work on server (probably using polymorphic setters)
- [ ] Fix animate to work on client
- [ ] Fix animate to work on server
- [ ] Bindiff for states over network (new delta algorithm) with statehistory
- [ ] Handle non-conforming components in the flex part

<a href="https://dashboard.polar.sh/alloverse/allonet/issues/24">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://dashboard.polar.sh/api/github/alloverse/allonet/issues/24/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://dashboard.polar.sh/api/github/alloverse/allonet/issues/24/pledge.svg">
</picture>
</a>

**Comment by nevyn** [comment]
![image](https://user-images.githubusercontent.com/34791/159942778-2a9918a2-9d27-46ea-989f-97cc6c207fbd.png)

I'm stuck here. This isn't doable. My ideas so far:

* Hard-code one "if" per known field. ew.
* Modify the schema generator to emit some sort of macro that iterates over each field. Ew
* Parse the flatbuffer into json, merge with the incoming json, parse back into flatbuffer. Ew.
* Make some sort of "variant" datastructure, modify the schema generator to emit stringly typed accessors to dive into the object tree by string. Uhhh that sounds super complicated, especially with smart pointers.
* Throw the whole damn thing away and rewrite in swift, and use dynamic dispatch in that language. well, probably not...
* give up and go home

**Comment by nevyn** [comment]
After long conversations with @Voxar:

* The split between components that have schema, and components that have to live in the "flex" part, is not nice, especially if we decide to incorporate things into the schema that previously were in flex. Statically compiled languages might even end up crashing or think data is missing.
* ProtoBuf has `Any`, and also Arena Allocation. Might be worth investigating as an alternative to Flatbuffers.
* Flexbuffers are also build-ahead-of-time, so they might not be so good for "non-specced components"
* Animations could continue being completely done on flatbuffers, and if you want write-back to the `next` tree, you request that per-value somehow
* Perhaps the best approach now is to just do a bunch of copy-pasted if's for changeComponents, and have in mind that this is an intermediate iteration of the protocol that WILL change. And try to hide the implementation details from clients.

**Comment by nevyn** [comment]
The todo list is stuck in Eventual Consistency Void, so here's a copy of it with edits:

- [x] Stub out missing methods
- [ ] Make the server run okay
    - [x] spawn entity
    - [x] Change components
    - [ ] removeEntity() 
    - [ ] add_property_animation_interaction
    - [ ] remove_property_animation_interaction
    - [ ] list_agents_interaction 
- [x] Merge luajitted master to flatbuffer branch
- [ ] Add flatbuffer support to the new ffi API
    - [ ] **NTH** maybe investigate IterationVisitor
    - [ ] client must calculate a state_diff from a previous state
        - [x] new_entities
        - [x] removed_entities
        - [x] new_components
        - [x] removed_components
        - [x] updated_components using UnPack
        - [ ] **NTH** figure out how to compare component Tables so we can implement updated_components
    - [x] Put a flatbuffer pointer in `olddata` and `newdata` in `component_ref`
    - [ ] use this diff in `Client:updateState`
- [ ] Fix `allosim_simulate_root_pose`
- [ ] Fix simulate to work on client
- [ ] Fix simulate to work on server (probably using polymorphic setters)
- [ ] Fix animate to work on client
- [ ] Fix animate to work on server
- [ ] Bindiff for states over network (new delta algorithm) with statehistory
- [ ] Handle non-conforming components in the flex part

**Comment by nevyn** [comment]
Flatbuffers are not a good match. Closing this.
